@API_URL = http://localhost:3000

### Sign up
POST {{API_URL}}/auth/signup
Content-Type: application/json; charset=utf-8

{
    "email":"test@sample.com",
    "password":"sample"
}


### Sign In
POST {{API_URL}}/auth/signin
Content-Type: application/json; charset=utf-8

{
    "email": "test@sample.com",
    "password": "sample"
}

### User ME
GET {{API_URL}}/users/me
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjc4NjQwNzI1LCJleHAiOjE2Nzg2NDE2MjV9.kkRD6v690pSTWjLG73QZNUmQwI4bDHT3y6Vkarufamk