@API_URL = http://localhost:3000

### Sign up
POST {{API_URL}}/auth/signup
Content-Type: application/json; charset=utf-8

{
    "email":"sample@sample.com",
    "password":"1234"
}


### Sign In
POST {{API_URL}}/auth/signin