@API_URL = http://localhost:3000

### Sign up
POST {{API_URL}}/auth/signup
Content-Type: application/json; charset=utf-8

{
    "email":"test@sample.com",
    "password":"sample"
}


### Sign In
POST {{API_URL}}/auth/signin
Content-Type: application/json; charset=utf-8

{
    "email": "test@sample.com",
    "password": "sample"
}

### User ME
GET {{API_URL}}/users/me
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoidGVzdEBzYW1wbGUuY29tIiwiaWF0IjoxNjc4OTQzMzk2LCJleHAiOjE2Nzg5NDQyOTZ9.h3WvP7xhHsXRM_TlhXDttMk7fP4CjQAdsGB0eEVA9VE