### test function call
GET http://localhost:8888/.netlify/functions/api

### Redirects
GET http://localhost:8888/


### GET USER
POST http://localhost:8888/.netlify/functions/registerUser
Content-Type: application/json

{
    "username":"jane",
    "password":"jane123",
    "email": "jane@test.com"
}

### Login USER
POST http://localhost:8888/.netlify/functions/login
Content-Type: application/json

{
    "email": "jane@test.com",
    "password":"jane123"

}

### Create USER
POST http://localhost:8888/.netlify/functions/createUser
Content-Type: application/json

{
    "username":"tester",
    "password":"123",
    "email":"testing@test.com"
}