### test function call
GET http://localhost:8888/.netlify/functions/api

### Redirects
GET http://localhost:8888/


### Create a User
POST http://localhost:8888/.netlify/functions/registerUser
Content-Type: application/json

{
    "username":"jack",
    "password":"jack1123",
    "email": "jack@test.com"
}

### Login USER
POST http://localhost:8888/.netlify/functions/login
Content-Type: application/json

{
    "email": "jack@test.com",
    "password":"jack1123"

}


### Update USER
PUT http://localhost:8888/.netlify/functions/users/6381be98b737eaeeee4d0d89
Content-Type: application/json

{
    "isAdmin": true,
    "userId": "6381be98b737eaeeee4d0d89"
}

### Delete USER
DELETE http://localhost:8888/.netlify/functions/users/6381be98b737eaeeee4d0d89
Content-Type: application/json

{
    "userId": "6381be98b737eaeeee4d0d89"
}

### Get User By Id
GET http://localhost:8888/.netlify/functions/users/63822d66f21ad9a340f75da8

### Follow User
PUT http://localhost:8888/.netlify/functions/followUser?userId=63822d66f21ad9a340f75da8
Content-Type: application/json

{
    "userId": "638250f5ab0f2716a7b7a1d8"
}

### UnFollow User
PUT http://localhost:8888/.netlify/functions/unfollowUser?userId=63822d66f21ad9a340f75da8
Content-Type: application/json

{
    "userId": "638250f5ab0f2716a7b7a1d8"
}
### Create another User 638250f5ab0f2716a7b7a1d8
POST http://localhost:8888/.netlify/functions/registerUser
Content-Type: application/json

{
    "username":"john",
    "password":"john123",
    "email": "john@test.com"
}


### GET POSTS
GET http://localhost:8888/.netlify/functions/posts/11