### test function call
GET http://localhost:8888/.netlify/functions/api

### Redirects
GET http://localhost:8888/


### Create a User
POST http://localhost:8888/.netlify/functions/registerUser
Content-Type: application/json

{
    "username":"jack",
    "password":"jack1123",
    "email": "jack@test.com"
}

### Login USER
POST http://localhost:8888/.netlify/functions/login
Content-Type: application/json

{
    "email": "jack@test.com",
    "password":"jack1123"

}


### Update USER
PUT http://localhost:8888/.netlify/functions/users/6381be98b737eaeeee4d0d89
Content-Type: application/json

{
    "isAdmin": true,
    "userId": "6381be98b737eaeeee4d0d89"
}