# This file configures your Netlify deploy
# Settings declared here override everything on Dashboard interface
# https://docs.netlify.com/configure-builds/file-based-configuration/
[build]
    functions="/functions"
[[redirects]]
  from = "/"
  to = "/.netlify/functions/app"
  status = 200