[build]
    functions="/functions"
[[redirects]]
    to="/.netlify/functions/app/:splat"
    from="/api/*"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"